### ISSUE TITLE
Approximate Training Time

### ISSUE THREAD

**Issue by sandylaker** [gaopengcuhk/BALLAD#2]
Hi. May I ask how long does it take to train the model with setting "ResNet50×16" on ImageNet-LT using an 8xA100 or 8xV100 server?

I would appreciate it a lot if you could provide me an approximate training time.

**Comment by TeleeMa** [comment]
@sandylaker With batch_size=64, it takes around 24 hours to train ResNet50×16 on ImageNet-LT using a single A100. As the code base is constructed using DP rather than DDP, using multi-gpus will not accelerate but only distribute the memory.

**Comment by sandylaker** [comment]
thanks
